[package]
name = "bikeroute-wasm"
version = "0.1.0"
authors = ["Angus Chiu"]
description = "Offline Turn-based Navigation for bike routes"
license = "MIT Or Apache-2.0"
repository = "https://github.com/anguschiu/bikeroute-wasm"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
